server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barberapp_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent-output: true
jwt:
  secret: